- name: Configure System
  hosts: head
  become: true
  tasks:

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_only: true

    - name: Prep base systems
      ansible.builtin.dnf:
        name:
          - yum-utils # AlmaLinux
          - dnf-plugins-core
          - python3-pip
          - vim

    - name: Check if reboot is required
      ansible.builtin.command: /usr/bin/needs-restarting -r
      register: needs_reboot
      changed_when: false
      failed_when: needs_reboot.rc == 1

    - name: Reboot system
      ansible.builtin.reboot:
      when: needs_reboot.rc
